//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ProtoColor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PROCOTYPE                   129
#define IDR_TOOLBAR1                    130
#define IDB_UNLOCKED_UP                 131
#define IDB_UNLOCKED_DN                 132
#define IDB_LOCKED_DN                   133
#define IDB_LOCKED_UP                   134
#define IDB_AR                          135
#define IDB_AR_TL                       136
#define IDB_AR_TB                       137
#define IDB_AR_TLB                      138
#define IDB_AR_TLBR                     139
#define IDB_AR_TR                       140
#define IDB_AR_BR                       141
#define IDB_AR_TBR                      142
#define IDB_AR_LR                       143
#define IDB_AR_LB                       144
#define IDB_AR_RLB                      145
#define IDB_AR_TLR                      146
#define IDB_AR_TR_LB                    147
#define IDB_AR_TL_RB                    148
#define IDB_AR_TB_LR                    149
#define IDB_CO_CMYK                     150
#define IDB_CO_RGB                      151
#define IDB_CO_CMY                      152
#define IDB_LOCKEDX                     153
#define IDB_UNLOCKEDX                   154
#define IDB_SOLDIER                     155
#define IDD_COLOR_FORMAT                158
#define IDD_PAGE_LAYOUT                 159
#define IDD_COLOR_ORIENTATION           160
#define IDD_CELL_ASPECTS                161
#define IDD_VIEW_PAGE                   162
#define IDD_CBLOCK_LAYOUT               163
#define IDD_BLOCK_LAYOUT                164
#define IDD_MESSAGE_BOX                 165
#define IDD_RETRACT_REQ                 166
#define IDD_AUTHORIZE                   167
#define IDD_EULA                        168
#define IDD_FLASH_SCREEN                169
#define IDD_MY_STATUS_BAR               170
#define IDR_COLOR_TOOLBAR               175
#define IDC_COLOR_HELP                  1000
#define IDC_RADIO_RGB                   1001
#define IDC_RADIO_CMYK                  1002
#define IDC_RADIO_CMY                   1003
#define IDC_MAX_STEPS                   1004
#define IDC_OUTL_COLR                   1005
#define IDC_START_RA_L2R                1006
#define IDC_END_RA_L2R                  1007
#define IDC_START_RA_T2B                1008
#define IDC_END_RA_T2B                  1009
#define IDC_START_RA_F2L                1010
#define IDC_END_RA_F2L                  1011
#define IDC_START_RA_F2B                1012
#define IDC_END_RA_F2B                  1013
#define IDC_HONOR_REQ                   1014
#define IDC_PRESERVE_LAY                1015
#define IDC_AUTO_LOCK_RANGE             1016
#define IDC_COLOR_RESET                 1017
#define IDC_COMPUTE_COLOR               1018
#define IDC_COLOR_JUMP                  1019
#define IDC_DYN_L2R                     1020
#define IDC_DYN_T2B                     1021
#define IDC_DYN_F2L                     1022
#define IDC_DYN_F2B                     1023
#define IDC_LOCKED                      1024
#define IDC_LOCKED2                     1025
#define IDC_LOCKED3                     1026
#define IDC_LOCKED4                     1027
#define IDC_LOCKED5                     1028
#define IDC_LOCKED7                     1029
#define IDC_LOCKED8                     1030
#define IDC_LOCKED6                     1031
#define IDC_BUTTON1                     1032
#define IDC_PAGEW_EDIT                  1033
#define IDC_UNIT_COMB                   1034
#define IDC_PAGEH_EDIT                  1035
#define IDC_UNIT_COMB2                  1036
#define IDC_PAGE_COUNT                  1037
#define IDC_PAGINATE_CHK                1038
#define IDC_UPPER_M_EDIT                1039
#define IDC_UNIT_COMB3                  1040
#define IDC_LEFT_M_EDIT                 1041
#define IDC_UNIT_COMB4                  1042
#define IDC_LOWER_M_EDIT                1043
#define IDC_UNIT_COMB5                  1044
#define IDC_RIGHT_M_EDIT                1045
#define IDC_UNIT_COMB6                  1046
#define IDC_LAYOUT_RESET                1047
#define IDC_COMPUTE                     1048
#define IDC_LAYOUT_JUMP                 1049
#define IDC_LOCKED12                    1050
#define IDC_LOCKED13                    1051
#define IDC_LOCKED14                    1052
#define IDC_LOCKED15                    1053
#define IDC_CLICKABLE_STATIC            1054
#define IDC_ORIENT_HLP                  1055
#define IDC_L2R_STATIC                  1056
#define IDC_DIR_L2R                     1057
#define IDC_T2B_STATIC                  1058
#define IDC_DIR_T2B                     1059
#define IDC_F2L_STATIC                  1060
#define IDC_DIR_F2L                     1061
#define IDC_F2B_STATIC                  1062
#define IDC_DIR_F2B                     1063
#define IDC_ORIENT                      1064
#define IDC_SPIN1                       1065
#define IDC_CNS_ROW                     1066
#define IDC_CNS_COL                     1067
#define IDC_CNS_BLK                     1068
#define IDC_CNS_CBLK                    1069
#define IDC_FRQ_ROW                     1070
#define IDC_FRQ_COL                     1071
#define IDC_FRQ_BLK                     1072
#define IDC_FRQ_CBLK                    1073
#define IDC_ROW_COUNT                   1074
#define IDC_COLUMN_COUNT                1075
#define IDC_BLOCK_COUNT                 1076
#define IDC_C_BLOCK_COUNT               1077
#define IDC_FROM_COLOR                  1078
#define IDC_INT_SYNC                    1079
#define IDC_UNIT_MEAS_COMB1             1080
#define IDC_CELL_HEIGHT                 1081
#define IDC_UNIT_MEAS_COMB2             1082
#define IDC_CELL_RATIO                  1083
#define IDC_BLOCK_WIDTH                 1084
#define IDC_UNIT_MEAS_COMB3             1085
#define IDC_BLOCK_HEIGHT                1086
#define IDC_UNIT_MEAS_COMB4             1087
#define IDC_CNGL_BLOCK_W                1088
#define IDC_UNIT_MEAS_COMB5             1089
#define IDC_CNGL_BLOCK_H                1090
#define IDC_UNIT_MEAS_COMB6             1091
#define IDC_RESET                       1092
#define IDC_CALCULATE                   1093
#define IDC_JUMP                        1094
#define IDC_START_RANGE                 1095
#define IDC_LOCKED17                    1096
#define IDC_LOCKED18                    1097
#define IDC_LOCKED19                    1098
#define IDC_LOCKED20                    1099
#define IDC_LOCKED21                    1100
#define IDC_LOCKED22                    1101
#define IDC_LOCKED23                    1102
#define IDC_LOCKED24                    1103
#define IDC_LOCKED25                    1104
#define IDC_LOCKED26                    1105
#define IDC_CELL_W                      1107
#define IDC_CUR_PAGE_EDIT               1108
#define IDC_CBLK_ROWS_EDIT              1109
#define IDC_CBLOCK_ROWS_EDIT            1109
#define IDC_CBLOCK_COLS_EDIT            1110
#define IDC_CB_COLSP_EDIT               1111
#define IDC_CB_ROWSP_EDIT               1112
#define IDC_V_FRM_W_EDIT                1113
#define IDC_V_FRM_H_EDIT                1114
#define IDC_CB_W_EDIT                   1115
#define IDC_CB_H_EDIT                   1116
#define IDC_CBL_RESET_BN                1117
#define IDC_HELP_BN                     1118
#define IDC_CBLOCK_STATIC               1119
#define IDC_BCOLS_EDIT                  1120
#define IDC_BROWS_EDIT                  1121
#define IDC_B_COLSPACE_EDIT             1122
#define IDC_B_ROWSPACE_EDIT             1123
#define IDC_FRAME_W_EDIT                1124
#define IDC_FRAME_H_EDIT                1125
#define IDC_BLOCKW_EDIT                 1126
#define IDC_BLOCKH_EDIT                 1127
#define IDC_BL_RESET_BN                 1128
#define IDC_HELP_OLD					1129
#define IDC_BLK_LAYOUT_STATIC           1130
#define IDC_YES_BN                      1131
#define IDC_NO_BN                       1132
#define IDC_MESS_STATIC                 1133
#define IDC_F1_STATIC                   1134
#define IDC_F5_STATIC                   1135
#define IDC_F2_STATIC                   1136
#define IDC_F4_STATIC                   1137
#define IDC_ITEM2                       1138
#define IDC_REQ_VAL2                    1139
#define IDC_VAL2                        1140
#define IDC_ITEM3                       1141
#define IDC_REQ_VAL3                    1142
#define IDC_VAL3                        1143
#define IDC_VAL4                        1144
#define IDC_ITEM5                       1145
#define IDC_REQ_VAL5                    1146
#define IDC_VAL5                        1147
#define IDC_ITEM6                       1148
#define IDC_REQ_VAL6                    1149
#define IDC_VAL6                        1150
#define IDC_ITEM                        1151
#define IDC_REQ_VAL                     1152
#define IDC_VAL                         1153
#define IDC_DEL2                        1154
#define IDC_DEL3                        1155
#define IDC_DEL4                        1156
#define IDC_DEL5                        1157
#define IDC_DEL6                        1158
#define IDC_DEL1                        1159
#define IDC_RETRACT_CHECK1              1160
#define IDC_RETRACT_CHECK2              1161
#define IDC_RETRACT_CHECK3              1162
#define IDC_RETRACT_CHECK4              1163
#define IDC_RETRACT_CHECK5              1164
#define IDC_RETRACT_CHECK6              1165
#define IDC_ITEM4                       1166
#define IDC_REQ_VAL4                    1167
#define IDC_KEY_EDIT                    1168
#define IDC_EULA_EDIT                   1169
#define IDC_PROGRESS_STATIC             1170
#define IDC_CELL_COUNT_STATIC           1171
#define ID_COLOR_SPEC                   32771
#define ID_LAYOUT                       32772
#define ID_CELL_SPECS                   32773
#define ID_BLOCK_LAYOUT                 32774
#define ID_C_BLOCK_LAYOUT               32775
#define ID_SPECIFY_ORIENT               32776
#define ID_VIEW_PAGEFINDER              32777
#define ID_RGB_BUTTON                   32778
#define ID_CMYK_BUTTON                  32779
#define ID_CMY_BUTTON                   32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
